### PR TITLE
HA: Set Optional  ordering for Neutron startup

### PR DESCRIPTION
**Pull request by dirkmueller**
Neutron depends on Keystone and RabbitMQ to be started first

### CODE REVIEW

**Comment by rhafer** [comment]
The ```pacemaker_order``` in https://github.com/crowbar/barclamp-neutron/blob/master/chef/cookbooks/neutron/recipes/l3_ha.rb#L147 should also be adapted to use ```crowbar_pacemaker_order_only_existing``` (and include ```rabbitmq```?). 

(Note to self: This depends on https://github.com/crowbar/barclamp-pacemaker/pull/179)

**Comment by aspiers** [comment]
Are we targeting this for GM?  Would require proper QA.

**Comment by vuntz** [comment]
Submitted https://github.com/dirkmueller/barclamp-neutron/pull/1 for my fixes

**Comment by vuntz** [comment]
+1

**Pull request merged**
