### PR TITLE
Neutron ha tool timeout

### PR DESCRIPTION
**Pull request by jsuchome**
increase neutron-ha-tool start timeout to 120s

Backport of https://github.com/crowbar/crowbar-openstack/pull/344 and https://github.com/crowbar/crowbar-openstack/pull/347

### CODE REVIEW

**Comment by AbelNavarro** [comment]
+1

**Comment by aspiers** [comment]
+1 but what is up with this gate failure?  Seems to be a common problem now, and I don't see anything on the Jenkins Green board for it.

**Comment by aspiers** [comment]
Retriggered mkcloud rebuild to try to clear CI gate.

**Comment by AbelNavarro** [comment]
Failed CI looks unrelated to change. Retriggering.
Trello [card](https://trello.com/c/s9rAxq0j/171-c5-failed-cct-scenario-ssh-to-controller-node) for the jenkins failure.

**Comment by AbelNavarro** [comment]
CI still failing at the same point.

**Comment by aspiers** [comment]
Filed as https://trello.com/c/s9rAxq0j/171-c5-failed-cct-scenario-ssh-to-controller-node

**Comment by AbelNavarro** [comment]
Retriggered CI. This time will investigate in the jenkins slave.

**Comment by aspiers** [comment]
Gate will be fixed by https://github.com/SUSE-Cloud/cct/pull/53

**Pull request merged**
