### PR TITLE
Backport ovs related additions from crowbar-openstack

### PR DESCRIPTION
**Pull request by rhafer**
This depends on: https://github.com/crowbar/barclamp-network/pull/331

### CODE REVIEW

**Comment by rhafer** [comment]
@jdsn: It seems this repo is also missing some group. At least I am not able to set any labels here as well.

**Comment by jdsn** [comment]
@rhafer fixed

**Comment by rhafer** [comment]
Updated with the latest fixes from crowbar-openstack. This basically works now, but needs a bit more testing.
But at least the update case, including the schema migration is already tested. (I successfully installed all the required barclamps on an already deployed D:C:5 setup and triggerd a chef-client run on all nodes. Nothing broke, all running instance kept replying to pings)

**Comment by rhafer** [comment]
Rebased. This is now ready for review. Should be merged after https://github.com/crowbar/barclamp-network/pull/331 (that's why I leave the "do not merge label" on for now). CI will fail until the other PR is merged.

**Comment by mjura** [comment]
+1, but please wait for gating after https://github.com/crowbar/barclamp-network/pull/331 will be merged

**Comment by vuntz** [comment]
Hrm, I thought I had commented here... Would be good to retrigger the CI once the package is updated (other PR got merged).

**Comment by dirkmueller** [comment]
retriggered

**Comment by vuntz** [comment]
> retriggered

Actually, https://ci.suse.de/job/openstack-mkcloud/14099/ was built with this PR and the barclamp-nova PR (as both are needed), so this should be good.

**Comment by vuntz** [comment]
+1

**Comment by bmwiedemann** [comment]
:+1:  - it turned out that crowbar/barclamp-network#331 breaks things without this one, because enable_neutron_networks is undefined.

**Pull request merged**
