### PR TITLE
Fix interface mappings when floating is not on a VLAN (bsc#955811)

### PR DESCRIPTION
**Pull request by rhafer**
If "nova_floating" as "use_vlan" turned of and is configured to use the same
conduit as "nova_fixed" they need to be on the same "physnet" in neutron. Try
to find those cases, write the interface_mapping accordingly and adjust the
"net-create" parameters for that.

Partiall fix for: https://bugzilla.suse.com/show_bug.cgi?id=955811

(cherry picked from commit fb1cea50ca2467e8a3738fac201d74ead38053f9 in
crowbar-openstack)

### CODE REVIEW

**Comment by rhafer** [comment]
Backport of: https://github.com/crowbar/crowbar-openstack/pull/128

**Comment by rhafer** [comment]
Added a schema migration to cleanup the issues that https://github.com/crowbar/barclamp-neutron/pull/239 created

**Comment by vuntz** [comment]
+1

**Comment by aplanas** [comment]
+1

**Pull request merged**
