### PR TITLE
Neutron ha tool fix to tex

### PR DESCRIPTION
**Pull request by nkrinner**
Backport of https://github.com/crowbar/barclamp-neutron/pull/217

### CODE REVIEW

**Comment by jsuchome** [comment]
+1 (Tested with Cloud 5)

**Comment by vuntz** [comment]
+1

**Comment by vuntz** [comment]
Hrm, it seems we don't have the patched neutron-ha-tool for this yet, though?

**Comment by jsuchome** [comment]
https://build.opensuse.org/request/show/309525

**Pull request merged**
