### PR TITLE
Added asset symlinking and cleanup

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by mjura** [comment]
I have no idea what it does but indentations looks awesome :)

**Comment by mjura** [comment]
Travis failed, it is sad :(

**Comment by tboerger** [comment]
@mjura Yeah, but it's only failing because the 1.8 test case is still active. that have to be disabled as we don't need the 1.8 tests anymore.

**Comment by tboerger** [comment]
@mjura I have added a seperate commit for removing the unsupported ruby versions from travis testing.

**Pull request merged**
