### PR TITLE
Write network configuration to have wicked understand ovs (bsc#930986)

### PR DESCRIPTION
**Pull request by aplanas**
This is based on https://en.opensuse.org/Portal:Wicked/OpenvSwitch and
comment 9 in the bug.

https://bugzilla.suse.com/show_bug.cgi?id=930986
(cherry picked from commit e6d3d94947e1528724750e3dbc9fc53c5df8356a)

### CODE REVIEW

**Comment by ovisan** [comment]
+1

**Comment by rhafer** [comment]
According to https://github.com/crowbar/crowbar-openstack/pull/3#issuecomment-137975166 the wicked restart that this PR does breaks HA setups.

Also I am wondering if we really need to backport the fix to tex. We have a workaround already merged (https://github.com/crowbar/barclamp-neutron/commit/daf40ea008bf03f1dd1996e6895c85585d6185c9) that might be enough for tex. After all, this patch (or the alternative being implemented in https://github.com/crowbar/crowbar-core/pull/33) changes quite a bit of complex code. At least I would rather see it stable and proven to work in "master" before attempting a backport.

@aplanas, @vuntz does that make sense?

**Comment by aplanas** [comment]
@rhafer for me makes sense to continue testing it only in suse cloud 6.  But did you try a HUP to wicked instead of a full restart?

**Comment by vuntz** [comment]
> Also I am wondering if we really need to backport the fix to tex. We have a workaround already merged (daf40ea) that might be enough for tex

Actually, afaik, the workaround was not enough. Or am I misremembering?

**Comment by rhafer** [comment]
Ugh. I thought it was. But actually we might need the workaround for https://bugzilla.suse.com/show_bug.cgi?id=945219 as well.

**Comment by vuntz** [comment]
@rhafer should we kill this PR (since I believe you're working on this)?

**Comment by rhafer** [comment]
@vuntz yes please.

**Pull request closed without merging**
