### PR TITLE
Add support for Infoblox DDI

### PR DESCRIPTION
**Pull request by rhafer**
I am putting this up for review here. I am not sure if it makes sense yet to merge it as we are still missing some pieces on the neutron side.

### CODE REVIEW

**Comment by mjura** [comment]
:+1:

**Comment by dirkmueller** [comment]
+1

**Comment by tboerger** [comment]
LGTM

**Comment by rhafer** [comment]
I'll close this for now. Will reopen against the stoney branch and rebase when the missing Juno pieces appear.

**Pull request closed without merging**
