### PR TITLE
Allow deploying neutron-server on SLE12 nodes

### PR DESCRIPTION
**Pull request by vuntz**
This seems to just work fine.

Also: Stop providing api-paste.ini as cookbook_file

This was only needed for the versions where the file could be different
from the packaged one, which was a long time ago. This should also not
be an issue on upgrades (content is correct, so packages will overwrite
the file now).

### CODE REVIEW

**Comment by vuntz** [comment]
Smoketests passing in tempest; and 1525/1528 for full tests (with the 3 failures being the usual suspects). So looks pretty good.

**Comment by jsuchome** [comment]
Seems to work well. +1

**Comment by jsuchome** [comment]
Chaning to -1. After some time, controller node stopped responding. @mjura will file a bug report

**Comment by vuntz** [comment]
> Changing to -1. After some time, controller node stopped responding. See
https://bugzilla.suse.com/show_bug.cgi?id=930986

The bug mentions IP addresses not being assigned to the right interfaces, which would be a neutron-network issue, not a neutron-server issue.

**Comment by jsuchome** [comment]
Hm, we're using SLE12 neutron-network for some time already, so I didn't suspect it. The example at crowbar.c13 cloud is still there, if you want to investigate

**Comment by jsuchome** [comment]
(So, retracting my -1)

**Comment by kbaikov** [comment]
+1

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
